import 'package:intl/intl.dart';

/// Frappe date/datetime helpers shared by the attendance feature.
final DateFormat kFrappeDate = DateFormat('yyyy-MM-dd');
final DateFormat kFrappeDateTime = DateFormat('yyyy-MM-dd HH:mm:ss');
final DateFormat kHHmm = DateFormat('HH:mm');

DateTime dateOnly(DateTime d) => DateTime(d.year, d.month, d.day);

DateTime? _parseDt(dynamic v) {
  if (v == null) return null;
  final s = v.toString().trim();
  if (s.isEmpty) return null;
  return DateTime.tryParse(s);
}

/// A Frappe `Employee` row; `deviceId` is `attendance_device_id`.
/// Employees with no device ID are "Not tracked": the terminal cannot record
/// them, and HRMS never generates Attendance for them.
class TrackedEmployee {
  final String name;
  final String employeeName;
  final String department;
  final String? deviceId;
  final String? defaultShift;
  final String? image;

  const TrackedEmployee({
    required this.name,
    required this.employeeName,
    this.department = '',
    this.deviceId,
    this.defaultShift,
    this.image,
  });

  bool get isTracked => (deviceId ?? '').trim().isNotEmpty;

  String get initials {
    final parts = employeeName.trim().split(RegExp(r'\s+'))
      ..removeWhere((p) => p.isEmpty);
    if (parts.isEmpty) return '?';
    if (parts.length == 1) return parts.first.substring(0, 1).toUpperCase();
    return (parts.first.substring(0, 1) + parts.last.substring(0, 1))
        .toUpperCase();
  }

  factory TrackedEmployee.fromJson(Map<String, dynamic> j) => TrackedEmployee(
        name: (j['name'] ?? '').toString(),
        employeeName: (j['employee_name'] ?? j['name'] ?? '').toString(),
        department: (j['department'] ?? '').toString(),
        deviceId: j['attendance_device_id']?.toString(),
        defaultShift: j['default_shift']?.toString(),
        image: j['image']?.toString(),
      );
}

/// One raw punch (`Employee Checkin`). `logType` is empty on this site: staff
/// only press Check In and the shift's Alternating IN/OUT rule decides.
class EmployeeCheckin {
  final String name;
  final String employee;
  final DateTime time;
  final String logType;
  final String deviceId;
  final String shift;

  const EmployeeCheckin({
    required this.name,
    required this.employee,
    required this.time,
    this.logType = '',
    this.deviceId = '',
    this.shift = '',
  });

  factory EmployeeCheckin.fromJson(Map<String, dynamic> j) => EmployeeCheckin(
        name: (j['name'] ?? '').toString(),
        employee: (j['employee'] ?? '').toString(),
        time: _parseDt(j['time']) ?? DateTime.fromMillisecondsSinceEpoch(0),
        logType: (j['log_type'] ?? '').toString(),
        deviceId: (j['device_id'] ?? '').toString(),
        shift: (j['shift'] ?? '').toString(),
      );
}

/// One submitted `Attendance` row (one per employee per day, generated by the
/// HRMS scheduler after the shift's check-out window closes).
class AttendanceRecord {
  final String name;
  final String employee;
  final String employeeName;
  final DateTime date;
  final String status; // Present | Absent | On Leave | Half Day | Work From Home
  final double workingHours;
  final DateTime? inTime;
  final DateTime? outTime;
  final bool lateEntry;
  final bool earlyExit;
  final String shift;
  final String leaveType;

  const AttendanceRecord({
    required this.name,
    required this.employee,
    required this.employeeName,
    required this.date,
    required this.status,
    this.workingHours = 0,
    this.inTime,
    this.outTime,
    this.lateEntry = false,
    this.earlyExit = false,
    this.shift = '',
    this.leaveType = '',
  });

  factory AttendanceRecord.fromJson(Map<String, dynamic> j) => AttendanceRecord(
        name: (j['name'] ?? '').toString(),
        employee: (j['employee'] ?? '').toString(),
        employeeName: (j['employee_name'] ?? '').toString(),
        date: _parseDt(j['attendance_date']) ?? DateTime(1970),
        status: (j['status'] ?? '').toString(),
        workingHours: double.tryParse('${j['working_hours'] ?? 0}') ?? 0,
        inTime: _parseDt(j['in_time']),
        outTime: _parseDt(j['out_time']),
        lateEntry: '${j['late_entry'] ?? 0}' == '1',
        earlyExit: '${j['early_exit'] ?? 0}' == '1',
        shift: (j['shift'] ?? '').toString(),
        leaveType: (j['leave_type'] ?? '').toString(),
      );
}

/// The bits of a `Shift Type` the screen needs, so 08:00 / 08:15 are never
/// hardcoded.
class ShiftRules {
  final String name;
  final Duration start; // time of day
  final Duration end;
  final int graceMinutes; // late_entry_grace_period
  final int checkInBeforeMinutes; // begin_check_in_before_shift_start_time
  final String holidayList;

  const ShiftRules({
    required this.name,
    required this.start,
    required this.end,
    this.graceMinutes = 0,
    this.checkInBeforeMinutes = 0,
    this.holidayList = '',
  });

  /// Fallback used only when the Shift Type cannot be read.
  static const fallback = ShiftRules(
    name: 'General',
    start: Duration(hours: 8),
    end: Duration(hours: 20),
    graceMinutes: 15,
    checkInBeforeMinutes: 120,
  );

  static Duration _parseTime(dynamic v) {
    final parts = (v ?? '').toString().split(':');
    if (parts.length < 2) return Duration.zero;
    return Duration(
      hours: int.tryParse(parts[0]) ?? 0,
      minutes: int.tryParse(parts[1]) ?? 0,
      seconds: parts.length > 2 ? (int.tryParse(parts[2]) ?? 0) : 0,
    );
  }

  factory ShiftRules.fromJson(Map<String, dynamic> j) => ShiftRules(
        name: (j['name'] ?? '').toString(),
        start: _parseTime(j['start_time']),
        end: _parseTime(j['end_time']),
        graceMinutes: int.tryParse('${j['late_entry_grace_period'] ?? 0}') ?? 0,
        checkInBeforeMinutes:
            int.tryParse('${j['begin_check_in_before_shift_start_time'] ?? 0}') ??
                0,
        holidayList: (j['holiday_list'] ?? '').toString(),
      );

  DateTime startOn(DateTime day) => dateOnly(day).add(start);
  DateTime endOn(DateTime day) => dateOnly(day).add(end);

  /// Last moment a first punch still counts as on time.
  DateTime cutoffOn(DateTime day) =>
      startOn(day).add(Duration(minutes: graceMinutes));

  String get startLabel => _fmt(start);
  String get endLabel => _fmt(end);
  String get cutoffLabel => _fmt(start + Duration(minutes: graceMinutes));

  static String _fmt(Duration d) =>
      '${d.inHours.toString().padLeft(2, '0')}:${(d.inMinutes % 60).toString().padLeft(2, '0')}';
}
