/// Model for the **Work Order Item** child DocType.
///
/// ERPNext path: Manufacturing → Work Order → required_items (child table)
/// DocType name : `Work Order Item`  (istable: 1)
/// Parent       : `Work Order`
///
/// Each row represents one raw-material / component required to manufacture
/// the finished good defined on the parent Work Order.
/// The app uses this table to show the bill-of-materials snapshot on the
/// Work Order form and to pre-populate material transfer requests.
class WorkOrderItem {
  // ── Identity ──────────────────────────────────────────────────────────────
  /// Child-row document name (auto-generated by Frappe, e.g. `abc123xyz`).
  final String name;

  /// Link → Item. The raw-material / component item code.
  final String itemCode;

  /// Item description / display name (denormalised from Item master).
  final String itemName;

  // ── Quantities ────────────────────────────────────────────────────────────
  /// Required qty (calculated from BOM at Work Order creation time).
  final double requiredQty;

  /// Qty already transferred to the WIP warehouse.
  final double transferredQty;

  /// Qty that has been consumed (issued) against the Work Order.
  final double consumedQty;

  // ── Warehouse & source ────────────────────────────────────────────────────
  /// Source warehouse from which the item will be / was transferred.
  final String? sourceWarehouse;

  /// Link → UOM master.
  final String? uom;

  /// Stock UOM (may differ from [uom] when conversion is applied).
  final String? stockUom;

  /// Conversion factor between [uom] and [stockUom].
  final double conversionFactor;

  // ── BOM link ──────────────────────────────────────────────────────────────
  /// Sub-assembly BOM (populated for multi-level BOMs).
  final String? subcontractedItem;

  /// True when this item belongs to a sub-assembly (multi-level BOM).
  final bool isPhantomItem;

  // ── Status / misc ─────────────────────────────────────────────────────────
  final String? description;

  const WorkOrderItem({
    required this.name,
    required this.itemCode,
    required this.itemName,
    required this.requiredQty,
    required this.transferredQty,
    required this.consumedQty,
    this.sourceWarehouse,
    this.uom,
    this.stockUom,
    required this.conversionFactor,
    this.subcontractedItem,
    required this.isPhantomItem,
    this.description,
  });

  // ── Computed ──────────────────────────────────────────────────────────────

  /// Qty still to be transferred (required − already transferred).
  /// Clamped to [0, requiredQty] to guard against over-transfer.
  double get pendingTransferQty =>
      (requiredQty - transferredQty).clamp(0.0, requiredQty);

  /// True when all required qty has been transferred to the WIP warehouse.
  bool get isFullyTransferred => transferredQty >= requiredQty;

  /// True when all required qty has been consumed.
  bool get isFullyConsumed => consumedQty >= requiredQty;

  // ── Deserialization ───────────────────────────────────────────────────────

  factory WorkOrderItem.fromJson(Map<String, dynamic> json) {
    return WorkOrderItem(
      name:               json['name']                as String? ?? '',
      itemCode:           json['item_code']           as String? ?? '',
      itemName:           json['item_name']           as String? ?? '',
      requiredQty:        (json['required_qty']       as num?)?.toDouble() ?? 0.0,
      transferredQty:     (json['transferred_qty']    as num?)?.toDouble() ?? 0.0,
      consumedQty:        (json['consumed_qty']       as num?)?.toDouble() ?? 0.0,
      sourceWarehouse:    json['source_warehouse']    as String?,
      uom:                json['uom']                 as String?,
      stockUom:           json['stock_uom']           as String?,
      conversionFactor:   (json['conversion_factor']  as num?)?.toDouble() ?? 1.0,
      subcontractedItem:  json['subcontracted_item']  as String?,
      isPhantomItem:      (json['phantom_item']       as int? ?? 0) == 1,
      description:        json['description']         as String?,
    );
  }

  // ── Serialization ─────────────────────────────────────────────────────────
  // Only mutable fields relevant for material transfer payloads.

  Map<String, dynamic> toTransferPayload({double? overrideQty}) => {
    'item_code':          itemCode,
    'qty':                overrideQty ?? requiredQty,
    if (uom != null)             'uom':              uom,
    if (stockUom != null)        'stock_uom':        stockUom,
    if (sourceWarehouse != null) 'source_warehouse': sourceWarehouse,
    'conversion_factor':  conversionFactor,
  };

  @override
  String toString() =>
      'WorkOrderItem(itemCode: $itemCode, itemName: $itemName, '
      'requiredQty: $requiredQty, transferredQty: $transferredQty, '
      'consumedQty: $consumedQty)';
}
